[package]
name = "eid-server"
version = "0.1.0"
edition = "2024"

[dependencies]
# Web server framework
axum = { version = "0.8.3", features = ["macros"] }
axum-server = { version = "0.6.0", features = ["tls-rustls"] }

# Web framework dependencies
hyper = { version = "0.14", features = ["client", "http1"] }
tower-http = { version = "0.6.2", features = ["cors", "trace"] }

# Async runtime
tokio = { version = "1.38.0", features = ["full"] }
tokio-stream = "0.1.15"
tonic = "0.9.2"
tower = "0.4.13"

# Error handling
thiserror = "2.0.12"
color-eyre = "0.6"

# XML handling
quick-xml = { version = "0.37.5", features = ["serialize"] }

# Serialization / Deserialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.117"

# Configuration
config = "0.15"

# Logging and tracing
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }

# Utilities
uuid = { version = "1.6", features = ["v4", "serde"] }
chrono = { version = "0.4", features = ["serde"] }
base64 = "0.22.1"
rand = "0.9.1"

# TLS dependencies
rustls = "0.23.28"
tokio-rustls = "0.26.0"
rustls-pemfile = "1.0.4"
rcgen = "0.11.1"

# PSK dependencies
openssl = { version = "0.10", features = ["v111"] }
openssl-sys = "0.9"
tokio-openssl = "0.6"
http = "1.3.1"
bytes = "1.10.1"
futures-util = "0.3.31"
lazy_static = "1.4.0"
libc = "0.2"

# Hex dependencies
hex = "0.4"

[dev-dependencies]
http-body-util = "0.1"
reqwest = { version = "0.11.18", features = ["json"] }
once_cell = "1.19.0"
tempfile = "3.10.1"

[profile.dev.package.backtrace]
opt-level = 3
