[package]
name = "eid-server"
version = "0.1.0"
edition = "2024"

[dependencies]
# Web server framework
axum = { version = "0.8.3", features = ["macros"] }

# Web framework dependencies
hyper = { version = "0.14", features = ["client", "http1"] }
tower-http = { version = "0.6.2", features = ["trace", "cors"] }

# Async runtime
tokio = { version = "1", features = ["full"] }

# Error handling
thiserror = "2.0.12"
color-eyre = "0.6"

# XML handling
quick-xml = { version = "0.37.5", features = ["serialize"] }

# Serialization / Deserialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Configuration
config = "0.15"

# Logging and tracing
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt"] }

# Utilities
chrono = { version = "0.4", features = ["serde"] }
async-trait = "0.1"
uuid = { version = "1.7", features = ["v4"] }
hex = "0.4.3"
rand = "0.9.1"
reqwest = "0.12"
futures-util = "0.3.31"

# Session management
dashmap = "6.1"

[dev-dependencies]
http-body-util = "0.1"
reqwest = { version = "0.12", features = ["json"] }

[profile.dev.package.backtrace]
opt-level = 3
