[package]
name = "eid-server"
version = "0.1.0"
edition = "2024"

[dependencies]
# Web server framework
axum = { version = "0.8.4", features = ["macros"] }  # Align with your build output
axum-server = { version = "0.7.0", features = ["tls-rustls"] }  # Upgrade to support rustls 0.23

# Web framework dependencies
hyper = { version = "1.4", features = ["client", "http1"] }  # Update to match axum 0.8
tower-http = { version = "0.6.2", features = ["trace", "cors"] }

# Async runtime
tokio = { version = "1.40", features = ["full"] }
tokio-rustls = "0.25"  # Compatible with rustls 0.23

# Error handling
thiserror = "2.0.12"
color-eyre = "0.6"

# XML handling
quick-xml = { version = "0.31", features = ["serialize"] }

# Serialization / Deserialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Configuration
config = "0.15"

tempfile = "3.20.0"

# Logging and metrics
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt"] }
dotenvy = "0.15"
rustls-pemfile = "2.0"
rustls = { version = "0.23.28", features = ["ring"] }

# Utilities
uuid = { version = "1.6", features = ["v4", "serde"] }
chrono = { version = "0.4", features = ["serde"] }
base64 = "0.22"
rand = "0.9.1"
tower = "0.5"

# Cryptographic dependencies
ring = "0.17"
x509-parser = "0.15"
lru = "0.12"
hex = "0.4"
pem = "3.0"

flate2 = "1.0"
reqwest = { version = "0.12.8", features = ["json", "blocking", "rustls-tls"] }
async-trait = "0.1"
urlencoding = "2.1"
url = "2.5.4"
openssl = { version = "0.10", features = ["vendored"] }

once_cell = "1.19"

[dev-dependencies]
http-body-util = "0.1"
color-eyre = "0.6"
base64 = "0.22.1"
libflate = "2.1.0"
openssl = "0.10.72"

[profile.dev.package.backtrace]
opt-level = 3
