[package]
name = "eid-server"
version = "0.1.0"
edition = "2024"

[dependencies]
# Web server framework
axum = { version = "0.8", features = ["macros"] }
axum-server = { version = "0.7", features = ["tls-openssl"] }
tower = "0.5"
tower-http = { version = "0.6.4", features = ["trace", "cors"] }
reqwest = { version = "0.12", default-features = false, features = [
    "json",
    "rustls-tls",
] }

# Async runtime
tokio = { version = "1.46", features = ["full"] }

# Error handling
thiserror = "2.0"
color-eyre = "0.6"

# Serialization / Deserialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
quick-xml = { version = "0.37.5", features = ["serialize"] }

# Configuration
config = "0.15"

# Logging and metrics
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt"] }

# Miscellaneous utilities
async-trait = "0.1"
base64 = "0.22.1"
rand = "0.9.1"
chrono = { version = "0.4", features = ["serde"] }
uuid = { version = "1.6", features = ["v4", "serde"] }
hex = "0.4.3"
urlencoding = "2.1"
flate2 = "1.0"
dashmap = "6.1.0"

# Cryptographic utilities
ring = "0.17"
x509-parser = "0.17"
lru = "0.16"
openssl = { version = "0.10", features = ["vendored"] }
pkcs8 = "0.10"

# Cryptographic operations
aes = "0.8"
cmac = "0.7"
p256 = { version = "0.13", features = ["ecdsa"] }
bp256 = { version = "0.6.1", features = ["ecdsa"] }
bp384 = { version = "0.6.1", features = ["ecdsa"] }
elliptic-curve = { version = "0.13", features = ["ecdh"] }
sha1 = "0.10"
sha2 = "0.10"
hmac = "0.12"
digest = "0.10"
hex-literal = "1"

# ASN.1 encoding/decoding
der = "0.7"
x509-cert = "0.2"
rasn = "0.27"

# Utility crates
zeroize = { version = "1.7", features = ["zeroize_derive"] }

[dependencies.redis]
version = "0.32"
features = ["tokio-rustls-comp", "connection-manager"]

[dev-dependencies]
http-body-util = "0.1"

[profile.dev.package.backtrace]
opt-level = 3

urlencoding = "2.1"
flate2 = "1.0"
dashmap = "6.1.0"
