[package]
name = "eid-server"
version = "0.1.0"
edition = "2024"

[dependencies]
# Web server framework
axum = { version = "0.8.3", features = ["macros"] }
tokio = { version = "1", features = ["full"] }
tower = "0.5.2"
tower-http = { version = "0.6.2", features = ["trace"] }
hyper = { version = "0.14", features = ["client", "http1"] }

# SOAP handling
yaserde = "0.12"
yaserde_derive = "0.12"
quick-xml = "0.37.5"
# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Error handling
thiserror = "2.0.12"
anyhow = "1.0"

# Logging and tracing
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

# Utilities
uuid = { version = "1.6", features = ["v4", "serde"] }
chrono = { version = "0.4", features = ["serde"] }
base64 = "0.22.1"
rand = "0.9.1"

http-body = "1.0"
http-body-util = "0.1"

[dev-dependencies]
axum-test = "17.3.0"
http-body-util = "0.1"
