[package]
name = "eid-server"
version = "0.1.0"
edition = "2024"

[dependencies]
# Web server framework
axum = { version = "0.8.4", features = ["macros"] }
axum-server = { version = "0.7.0", features = ["tls-rustls"] }

# Web framework dependencies
tower-http = { version = "0.6.2", features = ["trace", "cors"] }
async-trait = "0.1"
reqwest = { version = "0.12.8", default-features = false, features = ["json", "rustls-tls"] }

# Async runtime
tokio = { version = "1.46", features = ["full"] }
# Error handling
thiserror = "2.0.12"
color-eyre = "0.6"

# XML handling
quick-xml = { version = "0.37.5", features = ["serialize"] }

# Serialization / Deserialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Configuration
config = "0.15"
redis = { version = "0.25", features = ["tokio-comp"] }

# Logging and metrics
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt"] }
dotenvy = "0.15"
rustls-pemfile = "2.0"
rustls = "0.23.28" 

# Utilities
chrono = { version = "0.4", features = ["serde"] }
uuid = { version = "1.17", features = ["v4"] }
hex = "0.4.3"
rand = "0.9.1"
urlencoding = "2.1"
flate2 = "1.0"

# Cryptographic dependencies
ring = "0.17"
x509-parser = "0.15"
lru = "0.12"
base64 = "0.22"
dashmap = "6.1"

[dev-dependencies]
http-body-util = "0.1"
base64 = "0.22"
reqwest = { version = "0.12.8", features = ["json", "blocking", "rustls-tls"] }

[profile.dev.package.backtrace]
opt-level = 3
